In [ ]:
import tensorflow as tf ;

In [ ]:
tensor_zero_d = tf.constant(4);
print(tensor_zero_d);

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,0,-3]);
print(tensor_one_d);

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [2,0,-3],
    [3,5,1],
    [2,0,-3],
    [3,5,1]
]);
print(tensor_two_d);

tf.Tensor(
[[ 2  0 -3]
 [ 3  5  1]
 [ 2  0 -3]
 [ 3  5  1]], shape=(4, 3), dtype=int32)


In [ ]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=3,
    dtype=tf.dtypes.float32,
    name=None,
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [ ]:
fill_tensor = tf.fill(
    [1,2,3],5,None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5]
  [5 5 5]]], shape=(1, 2, 3), dtype=int32)


In [12]:
random_tensor = tf.random.normal(
    [3,2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None,
)
print(random_tensor)

tf.Tensor(
[[-0.50085956  0.6698561 ]
 [-1.0944238  -0.18841663]
 [-1.0860924   0.663614  ]], shape=(3, 2), dtype=float32)


In [ ]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)


tf.Tensor(
[[[1 1 1]
  [1 1 1]]], shape=(1, 2, 3), dtype=int32)
